- name: This playbook will install nginx in Ubuntu, configure nginx to serve html pages from custom folder and deploy custom web page
  hosts: all 
  vars:
  - provisioner_tool: Docker
  - conf_mgr_tool: Ansible
  - greeting_msg: Welcome to DevOps!
  tasks:
  - name: Install nginx web server into Ubuntu ansible nodes
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    apt: name=nginx state=latest update_cache=yes

  - name: Install Extra Packages for Enterprise Linux(EPEL) in Rocky ansible nodes
    when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
    yum: name=epel-release state=latest

  - name: Install nginx web server into Rocky ansible nodes
    when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
    yum: name=nginx state=latest 

  - name: Start nginx web server in Ubuntu ansible nodes 
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    service: name=nginx state=started

  - name: Check if nginx web server is already running in Rocky ansible nodes
    when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
    shell: curl http://localhost:80
    register: output
    ignore_errors: yes

  - debug: var=output

  - name: Start nginx web server in Rocky ansible nodes 
    when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" and output.rc != 0 )
    shell: nginx 

  - name: Let's create the nginx custom web root folder 
    file: path=/var/html state=directory mode=0777

  - name: Configure nginx web server to use our custom folder to serve the web pages in Ubuntu
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    copy: src=default dest=/etc/nginx/sites-available/default 

  - name: Configure nginx web server to use our custom folder to serve the web pages in Rocky 
    when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Restart nginx web server to apply config changes in Ubuntu ansible nodes
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    service: name=nginx state=restarted

  - name: Restart nginx web server to apply config changes in Rocky ansible nodes
    when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
    shell: nginx -s stop && nginx 

  - name: Retrieve IP address of ansible node
    shell: hostname -i
    register: output

  - debug: var=output

  - name: Deploy custom web page into our custom nginx web root folder
    template: src=index.html.j2 dest=/var/html/index.html


